// frontend/src/components/Onboarding.tsx
import { useState } from "react";
import { invoke } from "@/lib/backend";
import { Server, ArrowRight, Loader2 } from "lucide-react";
import { AppSettings, Profile } from "../types";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";

interface OnboardingProps {
  settings: AppSettings;
  onComplete: () => void;
  onSettingsChange: (settings: AppSettings) => void;
}

function Onboarding({
  settings,
  onComplete,
  onSettingsChange,
}: OnboardingProps) {
  const [step, setStep] = useState(0);
  const [serverUrl, setServerUrl] = useState("http://127.0.0.1:3001");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [isRegistering, setIsRegistering] = useState(false);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSkip = async () => {
    const newSettings = { ...settings, skip_auth: true };
    await invoke("save_settings", { settings: newSettings });
    onComplete();
  };

  const checkServer = async () => {
    setIsLoading(true);
    setError("");
    try {
      let url = serverUrl;
      if (!url.startsWith("http")) {
        url = "http://" + url;
        setServerUrl(url);
      }
      setStep(1);
    } catch (_e) {
      setError("Could not reach server");
    } finally {
      setIsLoading(false);
    }
  };

  const handleAuth = async () => {
    setIsLoading(true);
    setError("");
    try {
      if (isRegistering) {
        await invoke("register_user", {
          server: serverUrl,
          username,
          password,
        });
        setIsRegistering(false);
        setError("Registration successful! Please log in.");
        setIsLoading(false);
        return;
      }

      const token = await invoke<string>("login_user", {
        server: serverUrl,
        username,
        password,
      });

      if (token) {
        const newSettings: AppSettings = {
          ...settings,
          auth_server: serverUrl,
          auth_token: token,
          skip_auth: false,
        };

        const profiles = (await invoke("get_profiles")) as Profile[];

        if (profiles.length > 0) {
          newSettings.pending_sync_upload = true;
          await invoke("save_settings", { settings: newSettings });
          onSettingsChange(newSettings);
          alert(
            "Sync configured! Please restart the application to upload your profiles."
          );
        } else {
          try {
            await invoke("pull_profiles_from_server", { settings: newSettings });
          } catch (e) {
            console.error("Failed to pull profiles:", e);
          }
          await invoke("save_settings", { settings: newSettings });
          onSettingsChange(newSettings);
        }

        onComplete();
      }
    } catch (e: unknown) {
      setError(String(e) || "An error occurred");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-background/40 backdrop-blur-2xl flex items-center justify-center p-6">
      <Card className="w-full max-w-md border-border/50 shadow-2xl">
        <CardHeader className="text-center space-y-4 pb-8">
          <div className="mx-auto flex items-center justify-center w-16 h-16 rounded-2xl bg-primary/10 text-primary">
            <Server size={32} />
          </div>
          <div className="space-y-2">
            <CardTitle className="text-3xl font-black tracking-tight">
              Welcome to NuggetVPN
            </CardTitle>
            <CardDescription className="text-base">
              {step === 0
                ? "Connect to your sync server to get started"
                : isRegistering
                  ? "Create your account"
                  : "Sign in to your account"}
            </CardDescription>
          </div>
        </CardHeader>

        <CardContent>
          {error && (
            <Alert variant="destructive" className="mb-6">
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          {step === 0 ? (
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="server-url">SERVER URL</Label>
                <Input
                  id="server-url"
                  type="text"
                  value={serverUrl}
                  onChange={(e) => setServerUrl(e.target.value)}
                  placeholder="http://your-server.com:3001"
                  className="h-12"
                />
              </div>

              <Button
                onClick={checkServer}
                disabled={isLoading}
                className="w-full h-12 text-base font-bold"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Checking...
                  </>
                ) : (
                  <>
                    Continue <ArrowRight size={18} className="ml-2" />
                  </>
                )}
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="username">USERNAME</Label>
                <Input
                  id="username"
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  className="h-12"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">PASSWORD</Label>
                <Input
                  id="password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="h-12"
                />
              </div>

              <Button
                onClick={handleAuth}
                disabled={isLoading}
                className="w-full h-12 text-base font-bold"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Processing...
                  </>
                ) : isRegistering ? (
                  "Create Account"
                ) : (
                  "Sign In"
                )}
              </Button>

              <div className="flex items-center justify-between pt-2">
                <Button
                  variant="ghost"
                  onClick={() => setStep(0)}
                  className="text-muted-foreground"
                >
                  Back
                </Button>
                <Button
                  variant="link"
                  onClick={() => {
                    setIsRegistering(!isRegistering);
                    setError("");
                  }}
                  className="text-primary"
                >
                  {isRegistering ? "Already have an account?" : "Need an account?"}
                </Button>
              </div>
            </div>
          )}
        </CardContent>

        <CardFooter className="justify-center pt-0">
          <Button
            variant="ghost"
            onClick={handleSkip}
            className="w-full text-muted-foreground"
          >
            Skip Synchronization
          </Button>
        </CardFooter>
      </Card>
    </div>
  );
}

export default Onboarding;

// src/components/Onboarding.svelte
<script lang="ts">
    import { invoke } from "@tauri-apps/api/core";
    import { Server, LogIn, UserPlus, ArrowRight, X } from "lucide-svelte";

    let { settings, oncomplete } = $props();

    let step = 0; // 0: Server URL, 1: Auth (Login/Register)
    let serverUrl = "http://127.0.0.1:3001";
    let username = "";
    let password = "";
    let isRegistering = false;
    let error = "";
    let isLoading = false;

    async function handleSkip() {
        settings.skip_auth = true;
        await invoke("save_settings", { settings });
        oncomplete();
    }

    async function checkServer() {
        isLoading = true;
        error = "";
        try {
            // Simple health check or just assume it's valid if we can reach it
            // For now, we'll just proceed to the next step
            // In a real app, you might want to ping the server here
            if (!serverUrl.startsWith("http")) {
                serverUrl = "http://" + serverUrl;
            }
            step = 1;
        } catch (e) {
            error = "Could not reach server";
        } finally {
            isLoading = false;
        }
    }

    async function handleAuth() {
        isLoading = true;
        error = "";
        try {
            if (isRegistering) {
                await invoke("register_user", {
                    server: serverUrl,
                    username,
                    password,
                });

                isRegistering = false;
                error = "Registration successful! Please log in.";
                isLoading = false;
                return;
            }

            // Login
            const token = await invoke("login_user", {
                server: serverUrl,
                username,
                password,
            });

            if (token) {
                settings.auth_server = serverUrl;
                settings.auth_token = token;
                settings.skip_auth = false;

                // Check for local profiles
                const profiles = (await invoke("get_profiles")) as any[];

                if (profiles.length > 0) {
                    // Existing user adding sync -> Push on next restart
                    settings.pending_sync_upload = true;
                    await invoke("save_settings", { settings });
                    // We can't easily force a restart here, so we just complete and let the main app handle notifications or the user restarts manually as instructed
                    // Maybe show a message?
                    alert(
                        "Sync configured! Please restart the application to upload your profiles.",
                    );
                } else {
                    // New user -> Pull profiles immediately
                    try {
                        await invoke("pull_profiles_from_server", { settings });
                    } catch (e) {
                        console.error("Failed to pull profiles:", e);
                        // Non-fatal, maybe just empty server
                    }
                    await invoke("save_settings", { settings });
                }

                oncomplete();
            }
        } catch (e: any) {
            error = e || "An error occurred";
        } finally {
            isLoading = false;
        }
    }
</script>

<div
    class="fixed inset-0 z-50 bg-[#0f0805] flex items-center justify-center p-6"
>
    <div class="w-full max-w-md">
        <!-- Header -->
        <div class="text-center mb-10">
            <div
                class="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-orange-500/10 text-orange-500 mb-6"
            >
                <Server size={32} />
            </div>
            <h1 class="text-3xl font-black text-white tracking-tight mb-2">
                Welcome to NuggetVPN
            </h1>
            <p class="text-zinc-500">
                {#if step === 0}
                    Connect to your sync server to get started
                {:else}
                    {isRegistering
                        ? "Create your account"
                        : "Sign in to your account"}
                {/if}
            </p>
        </div>

        <div
            class="bg-zinc-900/50 border border-white/5 rounded-2xl p-6 backdrop-blur-xl"
        >
            {#if error}
                <div
                    class="mb-4 p-3 bg-red-500/10 border border-red-500/20 rounded-lg text-red-400 text-sm text-center"
                >
                    {error}
                </div>
            {/if}

            {#if step === 0}
                <div class="space-y-4">
                    <div>
                        <label
                            class="block text-xs font-medium text-zinc-500 mb-1.5 uppercase tracking-wider"
                            >Server URL</label
                        >
                        <input
                            type="text"
                            bind:value={serverUrl}
                            placeholder="http://your-server.com:3001"
                            class="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-4 py-3 text-zinc-200 focus:outline-none focus:border-orange-500/50 transition-colors"
                        />
                    </div>

                    <button
                        onclick={checkServer}
                        disabled={isLoading}
                        class="w-full bg-orange-600 hover:bg-orange-500 text-white font-bold py-3.5 rounded-xl transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {#if isLoading}
                            Checking...
                        {:else}
                            Continue <ArrowRight size={18} />
                        {/if}
                    </button>
                </div>
            {:else}
                <div class="space-y-4">
                    <div>
                        <label
                            class="block text-xs font-medium text-zinc-500 mb-1.5 uppercase tracking-wider"
                            >Username</label
                        >
                        <input
                            type="text"
                            bind:value={username}
                            class="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-4 py-3 text-zinc-200 focus:outline-none focus:border-orange-500/50 transition-colors"
                        />
                    </div>
                    <div>
                        <label
                            class="block text-xs font-medium text-zinc-500 mb-1.5 uppercase tracking-wider"
                            >Password</label
                        >
                        <input
                            type="password"
                            bind:value={password}
                            class="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-4 py-3 text-zinc-200 focus:outline-none focus:border-orange-500/50 transition-colors"
                        />
                    </div>

                    <button
                        onclick={handleAuth}
                        disabled={isLoading}
                        class="w-full bg-orange-600 hover:bg-orange-500 text-white font-bold py-3.5 rounded-xl transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {#if isLoading}
                            Processing...
                        {:else}
                            {isRegistering ? "Create Account" : "Sign In"}
                        {/if}
                    </button>

                    <div class="flex items-center justify-between pt-2">
                        <button
                            onclick={() => (step = 0)}
                            class="text-sm text-zinc-500 hover:text-zinc-300 transition-colors"
                        >
                            Back
                        </button>
                        <button
                            onclick={() => {
                                isRegistering = !isRegistering;
                                error = "";
                            }}
                            class="text-sm text-orange-500 hover:text-orange-400 transition-colors font-medium"
                        >
                            {isRegistering
                                ? "Already have an account?"
                                : "Need an account?"}
                        </button>
                    </div>
                </div>
            {/if}
        </div>

        <div class="mt-6 text-center">
            <button
                onclick={handleSkip}
                class="w-full py-3 rounded-xl border border-zinc-800 text-zinc-400 hover:text-white hover:bg-zinc-800/50 transition-all font-medium text-sm"
            >
                Skip Synchronization
            </button>
        </div>
    </div>
</div>
